# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2023-04-05T15:38:14+00:00

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic.dataclasses import dataclass

from gcapi.model_base import BaseModel


@dataclass
class AlgorithmImage(BaseModel):
    pk: str
    url: str
    api_url: str
    algorithm: str
    created: str
    requires_gpu: Optional[bool]
    requires_memory_gb: Optional[int]
    import_status: str


@dataclass
class Answer(BaseModel):
    answer: Optional[Dict[str, Any]]
    api_url: str
    created: str
    creator: str
    display_set: Optional[str]
    pk: str
    question: str
    modified: str
    answer_image: str
    last_edit_duration: Optional[str]
    total_edit_duration: str
    is_ground_truth: bool


@dataclass
class AnswerRequest(BaseModel):
    answer: Optional[Dict[str, Any]]
    display_set: Optional[str]
    question: str
    last_edit_duration: Optional[str]


@dataclass
class Archive(BaseModel):
    pk: str
    name: str
    title: str
    algorithms: List[str]
    logo: str
    description: Optional[str]
    api_url: str
    url: str


class BlankEnum(Enum):
    field_ = ""


@dataclass
class BooleanClassificationAnnotation(BaseModel):
    id: str
    image: str
    grader: Optional[int]
    created: Optional[str]
    name: str
    value: bool


@dataclass
class BooleanClassificationAnnotationRequest(BaseModel):
    image: str
    grader: Optional[int]
    created: Optional[str]
    name: str
    value: bool


@dataclass
class CategoricalOption(BaseModel):
    id: int
    title: str
    default: Optional[bool]


@dataclass
class Challenge(BaseModel):
    title: Optional[str]
    short_name: str


class ColorInterpolationEnum(Enum):
    RGB = "RGB"
    HLS = "HLS"
    HLSpos = "HLSpos"
    HLSneg = "HLSneg"
    Constant = "Constant"


class ColorSpaceEnum(Enum):
    GRAY = "GRAY"
    RGB = "RGB"
    RGBA = "RGBA"
    YCBCR = "YCBCR"


@dataclass
class ComponentInterfaceValuePost(BaseModel):
    interface: str
    value: Optional[Dict[str, Any]]
    file: Optional[str]
    image: Optional[str]
    pk: int


@dataclass
class ComponentInterfaceValuePostRequest(BaseModel):
    interface: str
    value: Optional[Dict[str, Any]]
    file: Optional[bytes]
    image: Optional[str]
    upload_session: Optional[str]
    user_upload: Optional[str]


@dataclass
class DisplaySetPostRequest(BaseModel):
    reader_study: Optional[str]
    values: Optional[List[ComponentInterfaceValuePostRequest]]
    order: Optional[int]


@dataclass
class ETDRSGridAnnotation(BaseModel):
    id: str
    grader: Optional[int]
    created: Optional[str]
    image: str
    fovea: List[float]
    optic_disk: Optional[List[float]]


@dataclass
class ETDRSGridAnnotationRequest(BaseModel):
    grader: Optional[int]
    created: Optional[str]
    image: str
    fovea: List[float]
    optic_disk: Optional[List[float]]


class EyeChoiceEnum(Enum):
    OD = "OD"
    OS = "OS"
    U = "U"
    NA = "NA"


@dataclass
class Feedback(BaseModel):
    session: str
    screenshot: Optional[str]
    user_comment: str
    context: Optional[Dict[str, Any]]


@dataclass
class FeedbackRequest(BaseModel):
    session: str
    screenshot: Optional[bytes]
    user_comment: str
    context: Optional[Dict[str, Any]]


class FieldOfViewEnum(Enum):
    F1M = "F1M"
    F2 = "F2"
    F3M = "F3M"
    F4 = "F4"
    F5 = "F5"
    F6 = "F6"
    F7 = "F7"
    U = "U"


@dataclass
class Follow(BaseModel):
    pk: int
    flag: Optional[str]


@dataclass
class FollowRequest(BaseModel):
    flag: Optional[str]


@dataclass
class HangingProtocol(BaseModel):
    json_: Dict[str, Any]


@dataclass
class HangingProtocolRequest(BaseModel):
    json_: Dict[str, Any]


@dataclass
class ImageLevelAnnotationsForImage(BaseModel):
    quality: Optional[str]
    pathology: Optional[str]
    retina_pathology: Optional[str]
    oct_retina_pathology: Optional[str]
    text: Optional[str]


@dataclass
class ImageTextAnnotation(BaseModel):
    id: str
    created: Optional[str]
    grader: Optional[int]
    image: str
    text: str


@dataclass
class ImageTextAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: str
    text: str


class ImageTypeEnum(Enum):
    MHD = "MHD"
    TIFF = "TIFF"
    DZI = "DZI"


@dataclass
class ImagingModality(BaseModel):
    modality: str


@dataclass
class JobPost(BaseModel):
    pk: str
    inputs: List[ComponentInterfaceValuePost]
    status: str


@dataclass
class JobPostRequest(BaseModel):
    algorithm: str
    inputs: List[ComponentInterfaceValuePostRequest]


class LocationEnum(Enum):
    AF = "AF"
    AX = "AX"
    AL = "AL"
    DZ = "DZ"
    AS = "AS"
    AD = "AD"
    AO = "AO"
    AI = "AI"
    AQ = "AQ"
    AG = "AG"
    AR = "AR"
    AM = "AM"
    AW = "AW"
    AU = "AU"
    AT = "AT"
    AZ = "AZ"
    BS = "BS"
    BH = "BH"
    BD = "BD"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    BZ = "BZ"
    BJ = "BJ"
    BM = "BM"
    BT = "BT"
    BO = "BO"
    BQ = "BQ"
    BA = "BA"
    BW = "BW"
    BV = "BV"
    BR = "BR"
    IO = "IO"
    BN = "BN"
    BG = "BG"
    BF = "BF"
    BI = "BI"
    CV = "CV"
    KH = "KH"
    CM = "CM"
    CA = "CA"
    KY = "KY"
    CF = "CF"
    TD = "TD"
    CL = "CL"
    CN = "CN"
    CX = "CX"
    CC = "CC"
    CO = "CO"
    KM = "KM"
    CG = "CG"
    CD = "CD"
    CK = "CK"
    CR = "CR"
    CI = "CI"
    HR = "HR"
    CU = "CU"
    CW = "CW"
    CY = "CY"
    CZ = "CZ"
    DK = "DK"
    DJ = "DJ"
    DM = "DM"
    DO = "DO"
    EC = "EC"
    EG = "EG"
    SV = "SV"
    GQ = "GQ"
    ER = "ER"
    EE = "EE"
    SZ = "SZ"
    ET = "ET"
    FK = "FK"
    FO = "FO"
    FJ = "FJ"
    FI = "FI"
    FR = "FR"
    GF = "GF"
    PF = "PF"
    TF = "TF"
    GA = "GA"
    GM = "GM"
    GE = "GE"
    DE = "DE"
    GH = "GH"
    GI = "GI"
    GR = "GR"
    GL = "GL"
    GD = "GD"
    GP = "GP"
    GU = "GU"
    GT = "GT"
    GG = "GG"
    GN = "GN"
    GW = "GW"
    GY = "GY"
    HT = "HT"
    HM = "HM"
    VA = "VA"
    HN = "HN"
    HK = "HK"
    HU = "HU"
    IS = "IS"
    IN = "IN"
    ID = "ID"
    IR = "IR"
    IQ = "IQ"
    IE = "IE"
    IM = "IM"
    IL = "IL"
    IT = "IT"
    JM = "JM"
    JP = "JP"
    JE = "JE"
    JO = "JO"
    KZ = "KZ"
    KE = "KE"
    KI = "KI"
    KW = "KW"
    KG = "KG"
    LA = "LA"
    LV = "LV"
    LB = "LB"
    LS = "LS"
    LR = "LR"
    LY = "LY"
    LI = "LI"
    LT = "LT"
    LU = "LU"
    MO = "MO"
    MG = "MG"
    MW = "MW"
    MY = "MY"
    MV = "MV"
    ML = "ML"
    MT = "MT"
    MH = "MH"
    MQ = "MQ"
    MR = "MR"
    MU = "MU"
    YT = "YT"
    MX = "MX"
    FM = "FM"
    MD = "MD"
    MC = "MC"
    MN = "MN"
    ME = "ME"
    MS = "MS"
    MA = "MA"
    MZ = "MZ"
    MM = "MM"
    NA = "NA"
    NR = "NR"
    NP = "NP"
    NL = "NL"
    NC = "NC"
    NZ = "NZ"
    NI = "NI"
    NE = "NE"
    NG = "NG"
    NU = "NU"
    NF = "NF"
    KP = "KP"
    MK = "MK"
    MP = "MP"
    NO = "NO"
    OM = "OM"
    PK = "PK"
    PW = "PW"
    PS = "PS"
    PA = "PA"
    PG = "PG"
    PY = "PY"
    PE = "PE"
    PH = "PH"
    PN = "PN"
    PL = "PL"
    PT = "PT"
    PR = "PR"
    QA = "QA"
    RE = "RE"
    RO = "RO"
    RU = "RU"
    RW = "RW"
    BL = "BL"
    SH = "SH"
    KN = "KN"
    LC = "LC"
    MF = "MF"
    PM = "PM"
    VC = "VC"
    WS = "WS"
    SM = "SM"
    ST = "ST"
    SA = "SA"
    SN = "SN"
    RS = "RS"
    SC = "SC"
    SL = "SL"
    SG = "SG"
    SX = "SX"
    SK = "SK"
    SI = "SI"
    SB = "SB"
    SO = "SO"
    ZA = "ZA"
    GS = "GS"
    KR = "KR"
    SS = "SS"
    ES = "ES"
    LK = "LK"
    SD = "SD"
    SR = "SR"
    SJ = "SJ"
    SE = "SE"
    CH = "CH"
    SY = "SY"
    TW = "TW"
    TJ = "TJ"
    TZ = "TZ"
    TH = "TH"
    TL = "TL"
    TG = "TG"
    TK = "TK"
    TO = "TO"
    TT = "TT"
    TN = "TN"
    TR = "TR"
    TM = "TM"
    TC = "TC"
    TV = "TV"
    UG = "UG"
    UA = "UA"
    AE = "AE"
    GB = "GB"
    UM = "UM"
    US = "US"
    UY = "UY"
    UZ = "UZ"
    VU = "VU"
    VE = "VE"
    VN = "VN"
    VG = "VG"
    VI = "VI"
    WF = "WF"
    EH = "EH"
    YE = "YE"
    ZM = "ZM"
    ZW = "ZW"


@dataclass
class LookUpTable(BaseModel):
    pk: int
    slug: str
    title: str
    description: Optional[str]
    color: str
    alpha: str
    color_invert: Optional[str]
    alpha_invert: Optional[str]
    range_min: Optional[int]
    range_max: Optional[int]
    relative: Optional[bool]
    color_interpolation: Optional[ColorInterpolationEnum]
    color_interpolation_invert: Optional[ColorInterpolationEnum]


@dataclass
class Notification(BaseModel):
    read: Optional[bool]


@dataclass
class NotificationRequest(BaseModel):
    read: Optional[bool]


class NullEnum(Enum):
    NoneType_None = None


@dataclass
class OctRetinaImagePathologyAnnotation(BaseModel):
    id: str
    created: Optional[str]
    grader: Optional[int]
    image: str
    macular: Optional[bool]
    myopia: Optional[bool]
    optic_disc: Optional[bool]
    other: Optional[bool]
    layers: Optional[bool]


@dataclass
class OctRetinaImagePathologyAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: str
    macular: Optional[bool]
    myopia: Optional[bool]
    optic_disc: Optional[bool]
    other: Optional[bool]
    layers: Optional[bool]


@dataclass
class PaginatedAlgorithmImageList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[AlgorithmImage]]


@dataclass
class PaginatedAnswerList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Answer]]


@dataclass
class PaginatedArchiveList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Archive]]


@dataclass
class PaginatedFeedbackList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Feedback]]


@dataclass
class PaginatedFollowList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Follow]]


@dataclass
class PaginatedNotificationList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Notification]]


@dataclass
class Part(BaseModel):
    ETag: str
    PartNumber: int
    LastModified: str
    Size: int


@dataclass
class PartRequest(BaseModel):
    ETag: str
    PartNumber: int
    LastModified: str
    Size: int


@dataclass
class PatchedAnswerRequest(BaseModel):
    answer: Optional[Dict[str, Any]]
    display_set: Optional[str]
    question: Optional[str]
    last_edit_duration: Optional[str]


@dataclass
class PatchedArchiveItemPostRequest(BaseModel):
    archive: Optional[str]
    values: Optional[List[ComponentInterfaceValuePostRequest]]


@dataclass
class PatchedBooleanClassificationAnnotationRequest(BaseModel):
    image: Optional[str]
    grader: Optional[int]
    created: Optional[str]
    name: Optional[str]
    value: Optional[bool]


@dataclass
class PatchedDisplaySetPostRequest(BaseModel):
    reader_study: Optional[str]
    values: Optional[List[ComponentInterfaceValuePostRequest]]
    order: Optional[int]


@dataclass
class PatchedETDRSGridAnnotationRequest(BaseModel):
    grader: Optional[int]
    created: Optional[str]
    image: Optional[str]
    fovea: Optional[List[float]]
    optic_disk: Optional[List[float]]


@dataclass
class PatchedFollowRequest(BaseModel):
    flag: Optional[str]


@dataclass
class PatchedImageTextAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: Optional[str]
    text: Optional[str]


@dataclass
class PatchedNotificationRequest(BaseModel):
    read: Optional[bool]


@dataclass
class PatchedOctRetinaImagePathologyAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: Optional[str]
    macular: Optional[bool]
    myopia: Optional[bool]
    optic_disc: Optional[bool]
    other: Optional[bool]
    layers: Optional[bool]


@dataclass
class PatchedRetinaImagePathologyAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: Optional[str]
    oda_present: Optional[bool]
    myopia_present: Optional[bool]
    other_present: Optional[bool]
    rf_present: Optional[bool]


@dataclass
class PatchedSinglePolygonAnnotationRequest(BaseModel):
    value: Optional[List[List[float]]]
    annotation_set: Optional[str]
    z: Optional[float]
    interpolated: Optional[bool]


@dataclass
class PatchedUserUploadCompleteRequest(BaseModel):
    parts: Optional[List[PartRequest]]


@dataclass
class PatchedUserUploadPresignedURLsRequest(BaseModel):
    part_numbers: Optional[List[int]]


class PathologyEnum(Enum):
    C = "C"
    A = "A"
    Q = "Q"
    P = "P"


class PatientSexEnum(Enum):
    M = "M"
    F = "F"
    O = "O"


@dataclass
class Phase(BaseModel):
    challenge: Challenge
    slug: str
    title: str = "Challenge"


class QualityEnum(Enum):
    U = "U"
    F = "F"
    G = "G"


class QualityReasonEnum(Enum):
    BP = "BP"
    CA = "CA"
    PM = "PM"


@dataclass
class RawImageUploadSession(BaseModel):
    pk: str
    creator: Optional[int]
    status: str
    error_message: Optional[str]
    image_set: List[str]
    api_url: str
    user_uploads: Optional[List[str]]
    uploads: List[str]


@dataclass
class RawImageUploadSessionRequest(BaseModel):
    creator: Optional[int]
    error_message: Optional[str]
    user_uploads: Optional[List[str]]
    archive: Optional[str]
    answer: Optional[str]
    interface: Optional[str]
    archive_item: Optional[str]
    display_set: Optional[str]
    uploads: List[str]


@dataclass
class RetinaImagePathologyAnnotation(BaseModel):
    id: str
    created: Optional[str]
    grader: Optional[int]
    image: str
    oda_present: bool
    myopia_present: bool
    other_present: bool
    rf_present: Optional[bool]


@dataclass
class RetinaImagePathologyAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: str
    oda_present: bool
    myopia_present: bool
    other_present: bool
    rf_present: Optional[bool]


@dataclass
class Session(BaseModel):
    pk: str
    status: str


@dataclass
class SimpleImage(BaseModel):
    pk: str
    name: str


@dataclass
class SingleLandmarkAnnotationSerializerNoParent(BaseModel):
    id: str
    image: str
    landmarks: List[List[float]]


@dataclass
class SingleLandmarkAnnotationSerializerNoParentRequest(BaseModel):
    image: str
    landmarks: List[List[float]]


@dataclass
class SinglePolygonAnnotation(BaseModel):
    id: str
    value: List[List[float]]
    annotation_set: str
    created: str
    z: Optional[float]
    interpolated: Optional[bool]


@dataclass
class SinglePolygonAnnotationRequest(BaseModel):
    value: List[List[float]]
    annotation_set: str
    z: Optional[float]
    interpolated: Optional[bool]


@dataclass
class SinglePolygonAnnotationSerializerNoParent(BaseModel):
    id: Optional[str]
    value: List[List[float]]
    z: Optional[float]
    interpolated: Optional[bool]


@dataclass
class SinglePolygonAnnotationSerializerNoParentRequest(BaseModel):
    id: Optional[str]
    value: List[List[float]]
    z: Optional[float]
    interpolated: Optional[bool]


class StereoscopicChoiceEnum(Enum):
    L = "L"
    R = "R"
    U = "U"


class TimezoneEnum(Enum):
    America_Araguaina = "America/Araguaina"
    Brazil_Acre = "Brazil/Acre"
    Asia_Chongqing = "Asia/Chongqing"
    Europe_Brussels = "Europe/Brussels"
    Etc_GMT_3 = "Etc/GMT-3"
    Asia_Makassar = "Asia/Makassar"
    Africa_Addis_Ababa = "Africa/Addis_Ababa"
    Australia_ACT = "Australia/ACT"
    Europe_Prague = "Europe/Prague"
    Africa_Ceuta = "Africa/Ceuta"
    America_Manaus = "America/Manaus"
    Asia_Chungking = "Asia/Chungking"
    Asia_Magadan = "Asia/Magadan"
    Antarctica_Davis = "Antarctica/Davis"
    Egypt = "Egypt"
    America_Scoresbysund = "America/Scoresbysund"
    America_Argentina_Cordoba = "America/Argentina/Cordoba"
    America_Argentina_ComodRivadavia = "America/Argentina/ComodRivadavia"
    Asia_Damascus = "Asia/Damascus"
    Etc_GMT_5 = "Etc/GMT-5"
    Pacific_Majuro = "Pacific/Majuro"
    Asia_Amman = "Asia/Amman"
    America_Vancouver = "America/Vancouver"
    America_Nipigon = "America/Nipigon"
    Europe_Podgorica = "Europe/Podgorica"
    America_Shiprock = "America/Shiprock"
    Asia_Istanbul = "Asia/Istanbul"
    Australia_Hobart = "Australia/Hobart"
    Pacific_Noumea = "Pacific/Noumea"
    America_Curacao = "America/Curacao"
    America_St_Johns = "America/St_Johns"
    America_Halifax = "America/Halifax"
    EST5EDT = "EST5EDT"
    America_Metlakatla = "America/Metlakatla"
    America_St_Vincent = "America/St_Vincent"
    Africa_Harare = "Africa/Harare"
    Etc_GMT_8 = "Etc/GMT-8"
    America_Argentina_Ushuaia = "America/Argentina/Ushuaia"
    Etc_GMT_2 = "Etc/GMT+2"
    Asia_Qatar = "Asia/Qatar"
    Asia_Tbilisi = "Asia/Tbilisi"
    HST = "HST"
    Africa_Lusaka = "Africa/Lusaka"
    Africa_Douala = "Africa/Douala"
    Australia_Adelaide = "Australia/Adelaide"
    America_Tegucigalpa = "America/Tegucigalpa"
    Australia_Lord_Howe = "Australia/Lord_Howe"
    America_Phoenix = "America/Phoenix"
    America_Regina = "America/Regina"
    Australia_North = "Australia/North"
    Pacific_Galapagos = "Pacific/Galapagos"
    America_Guatemala = "America/Guatemala"
    America_Recife = "America/Recife"
    Atlantic_Stanley = "Atlantic/Stanley"
    Brazil_DeNoronha = "Brazil/DeNoronha"
    America_Merida = "America/Merida"
    Hongkong = "Hongkong"
    Asia_Oral = "Asia/Oral"
    Etc_GMT_5_1 = "Etc/GMT+5"
    America_Argentina_Jujuy = "America/Argentina/Jujuy"
    Pacific_Enderbury = "Pacific/Enderbury"
    Etc_GMT_9 = "Etc/GMT+9"
    Asia_Chita = "Asia/Chita"
    Europe_Helsinki = "Europe/Helsinki"
    America_Louisville = "America/Louisville"
    America_Lower_Princes = "America/Lower_Princes"
    America_New_York = "America/New_York"
    America_Indiana_Knox = "America/Indiana/Knox"
    Europe_Vilnius = "Europe/Vilnius"
    America_Danmarkshavn = "America/Danmarkshavn"
    US_Arizona = "US/Arizona"
    Africa_Lome = "Africa/Lome"
    MST7MDT = "MST7MDT"
    America_St_Kitts = "America/St_Kitts"
    America_Argentina_Buenos_Aires = "America/Argentina/Buenos_Aires"
    Pacific_Pitcairn = "Pacific/Pitcairn"
    Europe_Stockholm = "Europe/Stockholm"
    Asia_Taipei = "Asia/Taipei"
    Africa_Kigali = "Africa/Kigali"
    Europe_Kirov = "Europe/Kirov"
    Africa_Djibouti = "Africa/Djibouti"
    Pacific_Gambier = "Pacific/Gambier"
    America_North_Dakota_Beulah = "America/North_Dakota/Beulah"
    Etc_GMT_13 = "Etc/GMT-13"
    America_Managua = "America/Managua"
    Asia_Ulan_Bator = "Asia/Ulan_Bator"
    Europe_Samara = "Europe/Samara"
    Asia_Baghdad = "Asia/Baghdad"
    America_Buenos_Aires = "America/Buenos_Aires"
    America_Puerto_Rico = "America/Puerto_Rico"
    America_Indiana_Indianapolis = "America/Indiana/Indianapolis"
    Pacific_Niue = "Pacific/Niue"
    America_Bahia = "America/Bahia"
    Canada_Mountain = "Canada/Mountain"
    GB_Eire = "GB-Eire"
    America_Argentina_Catamarca = "America/Argentina/Catamarca"
    America_Belem = "America/Belem"
    US_Indiana_Starke = "US/Indiana-Starke"
    America_Grenada = "America/Grenada"
    Europe_Moscow = "Europe/Moscow"
    Asia_Dili = "Asia/Dili"
    Asia_Ashkhabad = "Asia/Ashkhabad"
    Canada_Yukon = "Canada/Yukon"
    Asia_Yekaterinburg = "Asia/Yekaterinburg"
    US_Alaska = "US/Alaska"
    Brazil_East = "Brazil/East"
    America_Inuvik = "America/Inuvik"
    Australia_Queensland = "Australia/Queensland"
    Australia_Brisbane = "Australia/Brisbane"
    America_Mexico_City = "America/Mexico_City"
    Asia_Atyrau = "Asia/Atyrau"
    America_Kentucky_Louisville = "America/Kentucky/Louisville"
    Australia_Eucla = "Australia/Eucla"
    Etc_GMT_11 = "Etc/GMT-11"
    America_Cayenne = "America/Cayenne"
    Europe_Mariehamn = "Europe/Mariehamn"
    Etc_GMT_8_1 = "Etc/GMT+8"
    Asia_Calcutta = "Asia/Calcutta"
    Asia_Hebron = "Asia/Hebron"
    Etc_GMT_12 = "Etc/GMT+12"
    GB = "GB"
    Europe_London = "Europe/London"
    Etc_GMT_10 = "Etc/GMT-10"
    Pacific_Wallis = "Pacific/Wallis"
    Asia_Tel_Aviv = "Asia/Tel_Aviv"
    Turkey = "Turkey"
    Australia_Currie = "Australia/Currie"
    Europe_Tiraspol = "Europe/Tiraspol"
    Europe_Rome = "Europe/Rome"
    America_Resolute = "America/Resolute"
    America_Bahia_Banderas = "America/Bahia_Banderas"
    America_Noronha = "America/Noronha"
    Europe_Ulyanovsk = "Europe/Ulyanovsk"
    WET = "WET"
    America_Dawson_Creek = "America/Dawson_Creek"
    Asia_Dushanbe = "Asia/Dushanbe"
    Europe_Berlin = "Europe/Berlin"
    Asia_Phnom_Penh = "Asia/Phnom_Penh"
    Europe_Monaco = "Europe/Monaco"
    Iceland = "Iceland"
    Asia_Colombo = "Asia/Colombo"
    America_Maceio = "America/Maceio"
    America_Boa_Vista = "America/Boa_Vista"
    Antarctica_DumontDUrville = "Antarctica/DumontDUrville"
    America_Goose_Bay = "America/Goose_Bay"
    Chile_Continental = "Chile/Continental"
    Europe_Andorra = "Europe/Andorra"
    America_Hermosillo = "America/Hermosillo"
    Asia_Kolkata = "Asia/Kolkata"
    Universal = "Universal"
    Europe_Isle_of_Man = "Europe/Isle_of_Man"
    Australia_LHI = "Australia/LHI"
    America_Cayman = "America/Cayman"
    Asia_Dhaka = "Asia/Dhaka"
    Asia_Tomsk = "Asia/Tomsk"
    America_Guayaquil = "America/Guayaquil"
    America_Miquelon = "America/Miquelon"
    Africa_Nairobi = "Africa/Nairobi"
    Canada_Atlantic = "Canada/Atlantic"
    Asia_Baku = "Asia/Baku"
    America_Whitehorse = "America/Whitehorse"
    Etc_GMT_1 = "Etc/GMT-1"
    Australia_Yancowinna = "Australia/Yancowinna"
    Africa_Asmera = "Africa/Asmera"
    America_Detroit = "America/Detroit"
    Asia_Omsk = "Asia/Omsk"
    Africa_Malabo = "Africa/Malabo"
    America_Belize = "America/Belize"
    America_Porto_Velho = "America/Porto_Velho"
    Europe_Volgograd = "Europe/Volgograd"
    Asia_Kathmandu = "Asia/Kathmandu"
    Indian_Mauritius = "Indian/Mauritius"
    Asia_Kamchatka = "Asia/Kamchatka"
    America_Argentina_Salta = "America/Argentina/Salta"
    America_La_Paz = "America/La_Paz"
    Africa_Mbabane = "Africa/Mbabane"
    Europe_Paris = "Europe/Paris"
    Indian_Antananarivo = "Indian/Antananarivo"
    Singapore = "Singapore"
    Atlantic_Reykjavik = "Atlantic/Reykjavik"
    US_Michigan = "US/Michigan"
    Pacific_Bougainville = "Pacific/Bougainville"
    Pacific_Wake = "Pacific/Wake"
    Asia_Tehran = "Asia/Tehran"
    Antarctica_Mawson = "Antarctica/Mawson"
    Europe_Astrakhan = "Europe/Astrakhan"
    Europe_Bucharest = "Europe/Bucharest"
    Africa_Cairo = "Africa/Cairo"
    Antarctica_Casey = "Antarctica/Casey"
    Africa_Johannesburg = "Africa/Johannesburg"
    US_Hawaii = "US/Hawaii"
    Libya = "Libya"
    Pacific_Kwajalein = "Pacific/Kwajalein"
    MET = "MET"
    Canada_Pacific = "Canada/Pacific"
    Australia_Lindeman = "Australia/Lindeman"
    Asia_Sakhalin = "Asia/Sakhalin"
    Etc_GMT_7 = "Etc/GMT-7"
    Atlantic_Canary = "Atlantic/Canary"
    Pacific_Tahiti = "Pacific/Tahiti"
    Etc_GMT_4 = "Etc/GMT-4"
    America_Nuuk = "America/Nuuk"
    Australia_NSW = "Australia/NSW"
    America_Knox_IN = "America/Knox_IN"
    Asia_Muscat = "Asia/Muscat"
    Africa_Banjul = "Africa/Banjul"
    Africa_Juba = "Africa/Juba"
    America_North_Dakota_Center = "America/North_Dakota/Center"
    America_Argentina_La_Rioja = "America/Argentina/La_Rioja"
    America_Kentucky_Monticello = "America/Kentucky/Monticello"
    Africa_Abidjan = "Africa/Abidjan"
    Asia_Macau = "Asia/Macau"
    Pacific_Pohnpei = "Pacific/Pohnpei"
    America_Eirunepe = "America/Eirunepe"
    America_Blanc_Sablon = "America/Blanc-Sablon"
    America_Port_au_Prince = "America/Port-au-Prince"
    Australia_South = "Australia/South"
    Factory = "Factory"
    Pacific_Truk = "Pacific/Truk"
    Etc_GMT_2_1 = "Etc/GMT-2"
    Asia_Yakutsk = "Asia/Yakutsk"
    Africa_Blantyre = "Africa/Blantyre"
    Etc_GMT_12_1 = "Etc/GMT-12"
    Asia_Qostanay = "Asia/Qostanay"
    Asia_Barnaul = "Asia/Barnaul"
    Europe_Zaporozhye = "Europe/Zaporozhye"
    America_Argentina_Tucuman = "America/Argentina/Tucuman"
    US_Mountain = "US/Mountain"
    Europe_Budapest = "Europe/Budapest"
    Pacific_Ponape = "Pacific/Ponape"
    America_Martinique = "America/Martinique"
    Pacific_Yap = "Pacific/Yap"
    Africa_Maseru = "Africa/Maseru"
    Pacific_Tongatapu = "Pacific/Tongatapu"
    Asia_Thimbu = "Asia/Thimbu"
    Europe_Chisinau = "Europe/Chisinau"
    Asia_Kuala_Lumpur = "Asia/Kuala_Lumpur"
    US_East_Indiana = "US/East-Indiana"
    Asia_Yerevan = "Asia/Yerevan"
    NZ_CHAT = "NZ-CHAT"
    Asia_Hovd = "Asia/Hovd"
    America_Atka = "America/Atka"
    Indian_Christmas = "Indian/Christmas"
    America_Indianapolis = "America/Indianapolis"
    Asia_Bishkek = "Asia/Bishkek"
    Australia_Broken_Hill = "Australia/Broken_Hill"
    Japan = "Japan"
    W_SU = "W-SU"
    Pacific_Kosrae = "Pacific/Kosrae"
    Asia_Tokyo = "Asia/Tokyo"
    GMT = "GMT"
    Asia_Gaza = "Asia/Gaza"
    America_Indiana_Vincennes = "America/Indiana/Vincennes"
    America_Atikokan = "America/Atikokan"
    Africa_Sao_Tome = "Africa/Sao_Tome"
    Asia_Yangon = "Asia/Yangon"
    ROC = "ROC"
    Europe_Sarajevo = "Europe/Sarajevo"
    Africa_Khartoum = "Africa/Khartoum"
    Arctic_Longyearbyen = "Arctic/Longyearbyen"
    CET = "CET"
    Etc_GMT_7_1 = "Etc/GMT+7"
    America_Coral_Harbour = "America/Coral_Harbour"
    America_Winnipeg = "America/Winnipeg"
    America_Rio_Branco = "America/Rio_Branco"
    Africa_Kinshasa = "Africa/Kinshasa"
    America_Antigua = "America/Antigua"
    Pacific_Apia = "Pacific/Apia"
    America_Bogota = "America/Bogota"
    Australia_Victoria = "Australia/Victoria"
    Europe_Skopje = "Europe/Skopje"
    Africa_Ndjamena = "Africa/Ndjamena"
    Atlantic_Bermuda = "Atlantic/Bermuda"
    ROK = "ROK"
    Pacific_Chatham = "Pacific/Chatham"
    Africa_Tunis = "Africa/Tunis"
    Etc_Universal = "Etc/Universal"
    America_St_Lucia = "America/St_Lucia"
    Indian_Maldives = "Indian/Maldives"
    Pacific_Midway = "Pacific/Midway"
    Pacific_Norfolk = "Pacific/Norfolk"
    America_Asuncion = "America/Asuncion"
    America_Fort_Wayne = "America/Fort_Wayne"
    Africa_Monrovia = "Africa/Monrovia"
    US_Aleutian = "US/Aleutian"
    Pacific_Johnston = "Pacific/Johnston"
    Asia_Jakarta = "Asia/Jakarta"
    Asia_Ust_Nera = "Asia/Ust-Nera"
    Europe_Vaduz = "Europe/Vaduz"
    Asia_Hong_Kong = "Asia/Hong_Kong"
    Asia_Riyadh = "Asia/Riyadh"
    Africa_Timbuktu = "Africa/Timbuktu"
    America_Cancun = "America/Cancun"
    MST = "MST"
    America_Dominica = "America/Dominica"
    Asia_Samarkand = "Asia/Samarkand"
    America_Barbados = "America/Barbados"
    NZ = "NZ"
    Asia_Qyzylorda = "Asia/Qyzylorda"
    America_Denver = "America/Denver"
    America_Catamarca = "America/Catamarca"
    Asia_Vientiane = "Asia/Vientiane"
    Indian_Reunion = "Indian/Reunion"
    Atlantic_Azores = "Atlantic/Azores"
    Mexico_BajaSur = "Mexico/BajaSur"
    Mexico_General = "Mexico/General"
    Europe_Busingen = "Europe/Busingen"
    GMT_0 = "GMT+0"
    Asia_Kashgar = "Asia/Kashgar"
    Pacific_Fiji = "Pacific/Fiji"
    Asia_Novokuznetsk = "Asia/Novokuznetsk"
    Africa_Maputo = "Africa/Maputo"
    America_Iqaluit = "America/Iqaluit"
    America_Creston = "America/Creston"
    Indian_Kerguelen = "Indian/Kerguelen"
    America_Montevideo = "America/Montevideo"
    Pacific_Fakaofo = "Pacific/Fakaofo"
    Atlantic_Faroe = "Atlantic/Faroe"
    Asia_Almaty = "Asia/Almaty"
    America_Chihuahua = "America/Chihuahua"
    Indian_Mahe = "Indian/Mahe"
    Etc_GMT = "Etc/GMT"
    Asia_Famagusta = "Asia/Famagusta"
    America_Thunder_Bay = "America/Thunder_Bay"
    America_Los_Angeles = "America/Los_Angeles"
    Atlantic_Cape_Verde = "Atlantic/Cape_Verde"
    Asia_Jayapura = "Asia/Jayapura"
    Asia_Khandyga = "Asia/Khandyga"
    America_Fort_Nelson = "America/Fort_Nelson"
    Asia_Singapore = "Asia/Singapore"
    Asia_Tashkent = "Asia/Tashkent"
    Australia_Canberra = "Australia/Canberra"
    Etc_GMT_6 = "Etc/GMT+6"
    Asia_Kuwait = "Asia/Kuwait"
    Asia_Kuching = "Asia/Kuching"
    Antarctica_Troll = "Antarctica/Troll"
    America_Ensenada = "America/Ensenada"
    Etc_Zulu = "Etc/Zulu"
    Africa_Bangui = "Africa/Bangui"
    Etc_GMT_0 = "Etc/GMT-0"
    Africa_Algiers = "Africa/Algiers"
    Etc_GMT_14 = "Etc/GMT-14"
    America_Rainy_River = "America/Rainy_River"
    Europe_Madrid = "Europe/Madrid"
    Asia_Saigon = "Asia/Saigon"
    Zulu = "Zulu"
    Asia_Bangkok = "Asia/Bangkok"
    Asia_Nicosia = "Asia/Nicosia"
    Africa_Lubumbashi = "Africa/Lubumbashi"
    Indian_Chagos = "Indian/Chagos"
    Africa_Conakry = "Africa/Conakry"
    Europe_Amsterdam = "Europe/Amsterdam"
    Europe_Ljubljana = "Europe/Ljubljana"
    localtime = "localtime"
    Etc_UCT = "Etc/UCT"
    Africa_El_Aaiun = "Africa/El_Aaiun"
    America_Glace_Bay = "America/Glace_Bay"
    America_El_Salvador = "America/El_Salvador"
    CST6CDT = "CST6CDT"
    Pacific_Marquesas = "Pacific/Marquesas"
    Pacific_Guadalcanal = "Pacific/Guadalcanal"
    Etc_GMT0 = "Etc/GMT0"
    Asia_Ulaanbaatar = "Asia/Ulaanbaatar"
    Atlantic_South_Georgia = "Atlantic/South_Georgia"
    Pacific_Nauru = "Pacific/Nauru"
    America_Indiana_Petersburg = "America/Indiana/Petersburg"
    Jamaica = "Jamaica"
    America_Argentina_San_Luis = "America/Argentina/San_Luis"
    Africa_Libreville = "Africa/Libreville"
    EET = "EET"
    Asia_Harbin = "Asia/Harbin"
    Europe_Zurich = "Europe/Zurich"
    America_Edmonton = "America/Edmonton"
    Africa_Niamey = "Africa/Niamey"
    Europe_Luxembourg = "Europe/Luxembourg"
    Europe_Vienna = "Europe/Vienna"
    America_Aruba = "America/Aruba"
    Europe_Vatican = "Europe/Vatican"
    America_Argentina_Rio_Gallegos = "America/Argentina/Rio_Gallegos"
    Atlantic_Faeroe = "Atlantic/Faeroe"
    Africa_Tripoli = "Africa/Tripoli"
    Asia_Novosibirsk = "Asia/Novosibirsk"
    US_Pacific = "US/Pacific"
    Europe_Lisbon = "Europe/Lisbon"
    Asia_Ujung_Pandang = "Asia/Ujung_Pandang"
    US_Samoa = "US/Samoa"
    Europe_Guernsey = "Europe/Guernsey"
    Asia_Ashgabat = "Asia/Ashgabat"
    America_Campo_Grande = "America/Campo_Grande"
    Europe_Gibraltar = "Europe/Gibraltar"
    America_Sao_Paulo = "America/Sao_Paulo"
    America_Marigot = "America/Marigot"
    Etc_UTC = "Etc/UTC"
    Pacific_Samoa = "Pacific/Samoa"
    Europe_Riga = "Europe/Riga"
    Europe_Belgrade = "Europe/Belgrade"
    America_Adak = "America/Adak"
    Africa_Mogadishu = "Africa/Mogadishu"
    America_Costa_Rica = "America/Costa_Rica"
    EST = "EST"
    Australia_Sydney = "Australia/Sydney"
    Etc_GMT_3_1 = "Etc/GMT+3"
    Asia_Aqtau = "Asia/Aqtau"
    Canada_Central = "Canada/Central"
    Europe_Tirane = "Europe/Tirane"
    Asia_Dubai = "Asia/Dubai"
    America_Juneau = "America/Juneau"
    Pacific_Palau = "Pacific/Palau"
    Asia_Thimphu = "Asia/Thimphu"
    America_Kralendijk = "America/Kralendijk"
    Europe_Oslo = "Europe/Oslo"
    America_Havana = "America/Havana"
    Etc_GMT_1_1 = "Etc/GMT+1"
    Antarctica_Vostok = "Antarctica/Vostok"
    Europe_Saratov = "Europe/Saratov"
    Asia_Jerusalem = "Asia/Jerusalem"
    Europe_Dublin = "Europe/Dublin"
    Antarctica_South_Pole = "Antarctica/South_Pole"
    Asia_Beirut = "Asia/Beirut"
    Indian_Comoro = "Indian/Comoro"
    Europe_Istanbul = "Europe/Istanbul"
    Asia_Krasnoyarsk = "Asia/Krasnoyarsk"
    Pacific_Kanton = "Pacific/Kanton"
    America_Thule = "America/Thule"
    Indian_Cocos = "Indian/Cocos"
    Asia_Srednekolymsk = "Asia/Srednekolymsk"
    America_Jamaica = "America/Jamaica"
    America_Panama = "America/Panama"
    America_Port_of_Spain = "America/Port_of_Spain"
    America_Anchorage = "America/Anchorage"
    Africa_Lagos = "Africa/Lagos"
    America_Fortaleza = "America/Fortaleza"
    Pacific_Chuuk = "Pacific/Chuuk"
    America_Indiana_Vevay = "America/Indiana/Vevay"
    Cuba = "Cuba"
    Pacific_Rarotonga = "Pacific/Rarotonga"
    Etc_GMT_0_1 = "Etc/GMT+0"
    US_Central = "US/Central"
    Europe_Athens = "Europe/Athens"
    Europe_Tallinn = "Europe/Tallinn"
    Antarctica_Palmer = "Antarctica/Palmer"
    Australia_Perth = "Australia/Perth"
    Africa_Gaborone = "Africa/Gaborone"
    Asia_Anadyr = "Asia/Anadyr"
    Pacific_Kiritimati = "Pacific/Kiritimati"
    Europe_Jersey = "Europe/Jersey"
    Europe_Kyiv = "Europe/Kyiv"
    Asia_Katmandu = "Asia/Katmandu"
    Brazil_West = "Brazil/West"
    Africa_Accra = "Africa/Accra"
    Europe_Simferopol = "Europe/Simferopol"
    Canada_Saskatchewan = "Canada/Saskatchewan"
    Africa_Kampala = "Africa/Kampala"
    Canada_Eastern = "Canada/Eastern"
    Africa_Casablanca = "Africa/Casablanca"
    UTC = "UTC"
    America_Indiana_Winamac = "America/Indiana/Winamac"
    America_Toronto = "America/Toronto"
    America_Chicago = "America/Chicago"
    Etc_GMT_9_1 = "Etc/GMT-9"
    Africa_Dakar = "Africa/Dakar"
    Asia_Manila = "Asia/Manila"
    Indian_Mayotte = "Indian/Mayotte"
    Asia_Brunei = "Asia/Brunei"
    Pacific_Tarawa = "Pacific/Tarawa"
    Pacific_Saipan = "Pacific/Saipan"
    America_Montserrat = "America/Montserrat"
    America_North_Dakota_New_Salem = "America/North_Dakota/New_Salem"
    Asia_Bahrain = "Asia/Bahrain"
    Asia_Karachi = "Asia/Karachi"
    Atlantic_St_Helena = "Atlantic/St_Helena"
    Africa_Bissau = "Africa/Bissau"
    Etc_GMT_11_1 = "Etc/GMT+11"
    Pacific_Efate = "Pacific/Efate"
    Atlantic_Madeira = "Atlantic/Madeira"
    America_Paramaribo = "America/Paramaribo"
    Europe_Sofia = "Europe/Sofia"
    America_Anguilla = "America/Anguilla"
    America_Monterrey = "America/Monterrey"
    Pacific_Guam = "Pacific/Guam"
    GMT_0_1 = "GMT-0"
    Europe_Kaliningrad = "Europe/Kaliningrad"
    America_Menominee = "America/Menominee"
    Europe_Nicosia = "Europe/Nicosia"
    Africa_Porto_Novo = "Africa/Porto-Novo"
    Australia_Tasmania = "Australia/Tasmania"
    Africa_Windhoek = "Africa/Windhoek"
    Europe_Warsaw = "Europe/Warsaw"
    America_Santa_Isabel = "America/Santa_Isabel"
    Africa_Bujumbura = "Africa/Bujumbura"
    America_Santarem = "America/Santarem"
    Pacific_Easter = "Pacific/Easter"
    Pacific_Honolulu = "Pacific/Honolulu"
    America_Nassau = "America/Nassau"
    Asia_Irkutsk = "Asia/Irkutsk"
    America_Santo_Domingo = "America/Santo_Domingo"
    America_Caracas = "America/Caracas"
    Asia_Pyongyang = "Asia/Pyongyang"
    America_Yellowknife = "America/Yellowknife"
    America_Nome = "America/Nome"
    Africa_Bamako = "Africa/Bamako"
    Asia_Kabul = "Asia/Kabul"
    Portugal = "Portugal"
    America_Ojinaga = "America/Ojinaga"
    Etc_GMT_10_1 = "Etc/GMT+10"
    PRC = "PRC"
    America_Virgin = "America/Virgin"
    Antarctica_Syowa = "Antarctica/Syowa"
    US_Eastern = "US/Eastern"
    Asia_Urumqi = "Asia/Urumqi"
    America_Boise = "America/Boise"
    America_Dawson = "America/Dawson"
    America_Grand_Turk = "America/Grand_Turk"
    America_Montreal = "America/Montreal"
    America_St_Barthelemy = "America/St_Barthelemy"
    America_Cordoba = "America/Cordoba"
    America_Punta_Arenas = "America/Punta_Arenas"
    America_Mazatlan = "America/Mazatlan"
    GMT0 = "GMT0"
    America_Cuiaba = "America/Cuiaba"
    Europe_Copenhagen = "Europe/Copenhagen"
    Europe_San_Marino = "Europe/San_Marino"
    Africa_Freetown = "Africa/Freetown"
    Australia_Melbourne = "Australia/Melbourne"
    America_St_Thomas = "America/St_Thomas"
    America_Matamoros = "America/Matamoros"
    Etc_GMT_6_1 = "Etc/GMT-6"
    Asia_Pontianak = "Asia/Pontianak"
    America_Guadeloupe = "America/Guadeloupe"
    Asia_Seoul = "Asia/Seoul"
    America_Indiana_Marengo = "America/Indiana/Marengo"
    Chile_EasterIsland = "Chile/EasterIsland"
    Atlantic_Jan_Mayen = "Atlantic/Jan_Mayen"
    Europe_Uzhgorod = "Europe/Uzhgorod"
    America_Swift_Current = "America/Swift_Current"
    Africa_Dar_es_Salaam = "Africa/Dar_es_Salaam"
    PST8PDT = "PST8PDT"
    Africa_Nouakchott = "Africa/Nouakchott"
    Asia_Ho_Chi_Minh = "Asia/Ho_Chi_Minh"
    Antarctica_McMurdo = "Antarctica/McMurdo"
    Asia_Choibalsan = "Asia/Choibalsan"
    Pacific_Auckland = "Pacific/Auckland"
    Mexico_BajaNorte = "Mexico/BajaNorte"
    Asia_Vladivostok = "Asia/Vladivostok"
    Europe_Bratislava = "Europe/Bratislava"
    America_Sitka = "America/Sitka"
    America_Rankin_Inlet = "America/Rankin_Inlet"
    America_Jujuy = "America/Jujuy"
    America_Tijuana = "America/Tijuana"
    Africa_Luanda = "Africa/Luanda"
    Europe_Zagreb = "Europe/Zagreb"
    Asia_Macao = "Asia/Macao"
    Australia_West = "Australia/West"
    Africa_Ouagadougou = "Africa/Ouagadougou"
    Poland = "Poland"
    Asia_Shanghai = "Asia/Shanghai"
    Kwajalein = "Kwajalein"
    Australia_Darwin = "Australia/Darwin"
    America_Ciudad_Juarez = "America/Ciudad_Juarez"
    America_Porto_Acre = "America/Porto_Acre"
    Africa_Brazzaville = "Africa/Brazzaville"
    Africa_Asmara = "Africa/Asmara"
    Eire = "Eire"
    Europe_Belfast = "Europe/Belfast"
    Israel = "Israel"
    America_Argentina_San_Juan = "America/Argentina/San_Juan"
    Asia_Aden = "Asia/Aden"
    America_Guyana = "America/Guyana"
    Europe_Kiev = "Europe/Kiev"
    America_Yakutat = "America/Yakutat"
    America_Argentina_Mendoza = "America/Argentina/Mendoza"
    Antarctica_Rothera = "Antarctica/Rothera"
    Asia_Aqtobe = "Asia/Aqtobe"
    Pacific_Port_Moresby = "Pacific/Port_Moresby"
    America_Indiana_Tell_City = "America/Indiana/Tell_City"
    Europe_Minsk = "Europe/Minsk"
    Europe_Malta = "Europe/Malta"
    Asia_Rangoon = "Asia/Rangoon"
    Antarctica_Macquarie = "Antarctica/Macquarie"
    Etc_GMT_4_1 = "Etc/GMT+4"
    America_Cambridge_Bay = "America/Cambridge_Bay"
    Pacific_Pago_Pago = "Pacific/Pago_Pago"
    America_Pangnirtung = "America/Pangnirtung"
    America_Rosario = "America/Rosario"
    Canada_Newfoundland = "Canada/Newfoundland"
    America_Godthab = "America/Godthab"
    Navajo = "Navajo"
    UCT = "UCT"
    Greenwich = "Greenwich"
    America_Lima = "America/Lima"
    America_Tortola = "America/Tortola"
    Pacific_Funafuti = "Pacific/Funafuti"
    Etc_Greenwich = "Etc/Greenwich"
    America_Santiago = "America/Santiago"
    America_Mendoza = "America/Mendoza"
    Asia_Dacca = "Asia/Dacca"
    Iran = "Iran"
    America_Moncton = "America/Moncton"


@dataclass
class TimezoneRequest(BaseModel):
    timezone: TimezoneEnum


@dataclass
class User(BaseModel):
    username: str


@dataclass
class UserProfile(BaseModel):
    user: User
    mugshot: str
    institution: str
    department: str
    location: LocationEnum
    website: Optional[str]


@dataclass
class UserUpload(BaseModel):
    pk: str
    created: str
    filename: str
    key: str
    s3_upload_id: str
    status: str
    api_url: str


@dataclass
class UserUploadComplete(BaseModel):
    pk: str
    created: str
    filename: str
    key: str
    s3_upload_id: str
    status: str
    api_url: str


@dataclass
class UserUploadCreate(BaseModel):
    pk: str
    created: str
    filename: str
    key: str
    s3_upload_id: str
    status: str
    api_url: str


@dataclass
class UserUploadCreateRequest(BaseModel):
    filename: str


@dataclass
class UserUploadParts(BaseModel):
    pk: str
    created: str
    filename: str
    key: str
    s3_upload_id: str
    status: str
    api_url: str
    parts: List[Part]


@dataclass
class UserUploadPresignedURLs(BaseModel):
    pk: str
    created: str
    filename: str
    key: str
    s3_upload_id: str
    status: str
    api_url: str
    presigned_urls: Dict[str, str]


@dataclass
class WindowPreset(BaseModel):
    pk: int
    slug: str
    title: str
    description: Optional[str]
    center: Optional[int]
    width: Optional[int]
    lower_percentile: Optional[int]
    upper_percentile: Optional[int]


@dataclass
class Workstation(BaseModel):
    pk: str
    title: str
    slug: str
    url: str


@dataclass
class WorkstationConfig(BaseModel):
    pk: str
    slug: str
    title: str
    description: Optional[str]
    created: str
    modified: str
    creator: str
    image_context: str
    window_presets: List[WindowPreset]
    default_window_preset: WindowPreset
    default_slab_thickness_mm: float
    default_slab_render_method: str
    default_orientation: str
    default_overlay_alpha: float
    overlay_luts: List[LookUpTable]
    default_overlay_lut: LookUpTable
    default_overlay_interpolation: str
    default_image_interpolation: str
    overlay_segments: Optional[Dict[str, Any]]
    key_bindings: Optional[Dict[str, Any]]
    default_zoom_scale: float
    default_brush_size: Optional[Decimal]
    default_annotation_color: Optional[str]
    show_image_info_plugin: Optional[bool]
    show_display_plugin: Optional[bool]
    show_image_switcher_plugin: Optional[bool]
    show_algorithm_output_plugin: Optional[bool]
    show_overlay_plugin: Optional[bool]
    show_annotation_statistics_plugin: Optional[bool]
    show_swivel_tool: Optional[bool]
    show_invert_tool: Optional[bool]
    show_flip_tool: Optional[bool]
    show_window_level_tool: Optional[bool]
    show_reset_tool: Optional[bool]
    show_overlay_selection_tool: Optional[bool]
    show_lut_selection_tool: Optional[bool]
    show_annotation_counter_tool: Optional[bool]
    enabled_preprocessors: List[str]
    auto_jump_center_of_gravity: Optional[bool]
    link_images: Optional[bool]
    link_panning: Optional[bool]
    link_zooming: Optional[bool]
    link_slicing: Optional[bool]
    link_orienting: Optional[bool]
    link_windowing: Optional[bool]
    link_inverting: Optional[bool]
    link_flipping: Optional[bool]


@dataclass
class ArchiveItemPost(BaseModel):
    pk: str
    values: List[ComponentInterfaceValuePost]
    hanging_protocol: Optional[HangingProtocol]
    view_content: Dict[str, Any]


@dataclass
class ArchiveItemPostRequest(BaseModel):
    archive: str
    values: List[ComponentInterfaceValuePostRequest]


@dataclass
class ComponentInterface(BaseModel):
    title: str
    description: Optional[str]
    slug: str
    kind: str
    pk: int
    default_value: Optional[Dict[str, Any]]
    super_kind: str
    relative_path: str
    overlay_segments: Optional[Dict[str, Any]]
    look_up_table: Optional[LookUpTable]


@dataclass
class ComponentInterfaceValue(BaseModel):
    interface: ComponentInterface
    value: Optional[Dict[str, Any]]
    file: Optional[str]
    image: Optional[SimpleImage]
    pk: int


@dataclass
class DisplaySetPost(BaseModel):
    pk: str
    reader_study: Optional[str]
    values: Optional[List[ComponentInterfaceValuePost]]
    order: Optional[int]
    api_url: str
    hanging_protocol: Optional[HangingProtocol]
    view_content: Dict[str, Any]
    description: str
    index: Optional[int]


@dataclass
class HyperlinkedComponentInterfaceValue(BaseModel):
    interface: ComponentInterface
    value: Optional[Dict[str, Any]]
    file: Optional[str]
    image: Optional[str]
    pk: int


@dataclass
class HyperlinkedJob(BaseModel):
    pk: str
    api_url: str
    algorithm_image: str
    inputs: List[HyperlinkedComponentInterfaceValue]
    outputs: List[HyperlinkedComponentInterfaceValue]
    status: str
    rendered_result_text: str
    started_at: Optional[str]
    completed_at: Optional[str]
    hanging_protocol: Optional[HangingProtocol]
    view_content: Dict[str, Any]


@dataclass
class ImageFile(BaseModel):
    pk: str
    image: Optional[str]
    file: str
    image_type: Optional[ImageTypeEnum]


@dataclass
class ImagePathologyAnnotation(BaseModel):
    id: str
    created: Optional[str]
    grader: Optional[int]
    image: str
    pathology: PathologyEnum


@dataclass
class ImagePathologyAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: str
    pathology: PathologyEnum


@dataclass
class ImageQualityAnnotation(BaseModel):
    id: str
    created: Optional[str]
    grader: Optional[int]
    image: str
    quality: QualityEnum
    quality_reason: Optional[Union[QualityReasonEnum, BlankEnum, NullEnum]]


@dataclass
class ImageQualityAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: str
    quality: QualityEnum
    quality_reason: Optional[Union[QualityReasonEnum, BlankEnum, NullEnum]]


@dataclass
class LandmarkAnnotationSet(BaseModel):
    id: str
    grader: Optional[int]
    created: Optional[str]
    singlelandmarkannotation_set: List[
        SingleLandmarkAnnotationSerializerNoParent
    ]


@dataclass
class LandmarkAnnotationSetRequest(BaseModel):
    grader: Optional[int]
    created: Optional[str]
    singlelandmarkannotation_set: List[
        SingleLandmarkAnnotationSerializerNoParentRequest
    ]


@dataclass
class NestedPolygonAnnotationSet(BaseModel):
    id: str
    image: str
    grader: Optional[int]
    created: Optional[str]
    name: str
    singlepolygonannotation_set: List[
        SinglePolygonAnnotationSerializerNoParent
    ]


@dataclass
class NestedPolygonAnnotationSetRequest(BaseModel):
    image: str
    grader: Optional[int]
    created: Optional[str]
    name: str
    singlepolygonannotation_set: List[
        SinglePolygonAnnotationSerializerNoParentRequest
    ]


@dataclass
class PaginatedComponentInterfaceList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[ComponentInterface]]


@dataclass
class PaginatedHyperlinkedJobList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[HyperlinkedJob]]


@dataclass
class PaginatedRawImageUploadSessionList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[RawImageUploadSession]]


@dataclass
class PaginatedSessionList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Session]]


@dataclass
class PaginatedUserUploadList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[UserUpload]]


@dataclass
class PaginatedWorkstationConfigList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[WorkstationConfig]]


@dataclass
class PaginatedWorkstationList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Workstation]]


@dataclass
class PatchedImagePathologyAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: Optional[str]
    pathology: Optional[PathologyEnum]


@dataclass
class PatchedImageQualityAnnotationRequest(BaseModel):
    created: Optional[str]
    grader: Optional[int]
    image: Optional[str]
    quality: Optional[QualityEnum]
    quality_reason: Optional[Union[QualityReasonEnum, BlankEnum, NullEnum]]


@dataclass
class PatchedLandmarkAnnotationSetRequest(BaseModel):
    grader: Optional[int]
    created: Optional[str]
    singlelandmarkannotation_set: Optional[
        List[SingleLandmarkAnnotationSerializerNoParentRequest]
    ]


@dataclass
class PatchedNestedPolygonAnnotationSetRequest(BaseModel):
    image: Optional[str]
    grader: Optional[int]
    created: Optional[str]
    name: Optional[str]
    singlepolygonannotation_set: Optional[
        List[SinglePolygonAnnotationSerializerNoParentRequest]
    ]


@dataclass
class Question(BaseModel):
    answer_type: str
    api_url: str
    form_direction: str
    help_text: Optional[str]
    image_port: str
    pk: str
    question_text: str
    reader_study: str
    required: Optional[bool]
    options: List[CategoricalOption]
    interface: Optional[ComponentInterface]
    overlay_segments: Optional[Dict[str, Any]]
    look_up_table: Optional[LookUpTable]
    widget: str
    answer_min_value: Optional[int]
    answer_max_value: Optional[int]
    answer_step_size: Optional[Decimal]


@dataclass
class ReaderStudy(BaseModel):
    api_url: str
    url: str
    slug: str
    logo: str
    description: Optional[str]
    help_text: str
    pk: str
    questions: List[Question]
    title: str
    is_educational: Optional[bool]
    has_ground_truth: bool
    allow_answer_modification: Optional[bool]
    allow_case_navigation: Optional[bool]
    allow_show_all_annotations: Optional[bool]
    roll_over_answers_for_n_cases: Optional[int]


@dataclass
class RetinaImage(BaseModel):
    pk: str
    name: str
    files: List[ImageFile]
    width: int
    height: int
    depth: Optional[int]
    color_space: ColorSpaceEnum
    modality: Optional[ImagingModality]
    eye_choice: Optional[EyeChoiceEnum]
    stereoscopic_choice: Optional[
        Union[StereoscopicChoiceEnum, BlankEnum, NullEnum]
    ]
    field_of_view: Optional[Union[FieldOfViewEnum, BlankEnum, NullEnum]]
    shape_without_color: List[int]
    shape: List[int]
    voxel_width_mm: Optional[float]
    voxel_height_mm: Optional[float]
    voxel_depth_mm: Optional[float]
    api_url: str
    patient_id: Optional[str]
    patient_name: Optional[str]
    patient_birth_date: Optional[str]
    patient_age: Optional[str]
    patient_sex: Optional[Union[PatientSexEnum, BlankEnum]]
    study_date: Optional[str]
    study_instance_uid: Optional[str]
    series_instance_uid: Optional[str]
    study_description: Optional[str]
    series_description: Optional[str]
    window_center: Optional[float]
    window_width: Optional[float]
    landmark_annotations: List[str]


@dataclass
class Submission(BaseModel):
    pk: str
    phase: Phase
    created: str
    creator: User
    comment: Optional[str]
    predictions_file: str
    supplementary_file: Optional[str]
    supplementary_url: Optional[str]
    algorithm_image: str


@dataclass
class Timezone(BaseModel):
    timezone: TimezoneEnum


@dataclass
class Algorithm(BaseModel):
    api_url: str
    url: str
    description: Optional[str]
    pk: str
    title: str
    logo: str
    slug: str
    average_duration: Optional[float]
    inputs: List[ComponentInterface]
    outputs: List[ComponentInterface]


@dataclass
class ArchiveItem(BaseModel):
    pk: str
    archive: str
    values: List[HyperlinkedComponentInterfaceValue]
    hanging_protocol: Optional[HangingProtocol]
    view_content: Dict[str, Any]


@dataclass
class DisplaySet(BaseModel):
    pk: str
    reader_study: str
    values: List[HyperlinkedComponentInterfaceValue]
    order: Optional[int]
    api_url: str
    hanging_protocol: Optional[HangingProtocol]
    view_content: Dict[str, Any]
    description: str
    index: Optional[int]


@dataclass
class Evaluation(BaseModel):
    pk: str
    method: str
    submission: Submission
    created: str
    published: Optional[bool]
    outputs: List[ComponentInterfaceValue]
    rank: Optional[int]
    rank_score: Optional[float]
    rank_per_metric: Optional[Dict[str, Any]]
    status: str
    title: str


@dataclass
class HyperlinkedImage(BaseModel):
    pk: str
    name: str
    files: List[ImageFile]
    width: int
    height: int
    depth: Optional[int]
    color_space: ColorSpaceEnum
    modality: Optional[ImagingModality]
    eye_choice: Optional[EyeChoiceEnum]
    stereoscopic_choice: Optional[
        Union[StereoscopicChoiceEnum, BlankEnum, NullEnum]
    ]
    field_of_view: Optional[Union[FieldOfViewEnum, BlankEnum, NullEnum]]
    shape_without_color: List[int]
    shape: List[int]
    voxel_width_mm: Optional[float]
    voxel_height_mm: Optional[float]
    voxel_depth_mm: Optional[float]
    api_url: str
    patient_id: Optional[str]
    patient_name: Optional[str]
    patient_birth_date: Optional[str]
    patient_age: Optional[str]
    patient_sex: Optional[Union[PatientSexEnum, BlankEnum]]
    study_date: Optional[str]
    study_instance_uid: Optional[str]
    series_instance_uid: Optional[str]
    study_description: Optional[str]
    series_description: Optional[str]
    window_center: Optional[float]
    window_width: Optional[float]


@dataclass
class PaginatedAlgorithmList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Algorithm]]


@dataclass
class PaginatedArchiveItemList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[ArchiveItem]]


@dataclass
class PaginatedDisplaySetList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[DisplaySet]]


@dataclass
class PaginatedEvaluationList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Evaluation]]


@dataclass
class PaginatedHyperlinkedImageList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[HyperlinkedImage]]


@dataclass
class PaginatedQuestionList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[Question]]


@dataclass
class PaginatedReaderStudyList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[ReaderStudy]]


@dataclass
class PaginatedRetinaImageList(BaseModel):
    count: Optional[int]
    next: Optional[str]
    previous: Optional[str]
    results: Optional[List[RetinaImage]]
