default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.5.1
    hooks:
      - id: pyupgrade
        language: python
        args: [--py3-plus]
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language: python
