site_name: GCAPI Documentation
nav:
  - Home:
    - Overview: index.md
    - License: license.md
  - Getting Started: getting-started.md
  - Usage:
    - Archives:
      - Create Archive Items: usage/archive/create_archive_items.md
      - Update Archive Items: usage/archive/update_archive_items.md
      - Download Archive Items: usage/archive/download_archive_items.md
    - Reader Studies:
      - Create Display Sets: usage/reader_study/create_display_sets.md
      - Update Display Sets: usage/reader_study/update_display_sets.md
      - Re-use Display-Set Images: usage/reader_study/reuse_images_in_display_sets.md
      - Download Answers: usage/reader_study/download_answers.md
    - Algorithms:
      - Start Jobs: usage/algorithm/start_algorithm_jobs.md
      - Download Predictions: usage/algorithm/download_algorithm_predictions.md
  - Python API Reference:
    - Methods: api/client_methods.md
    - APIs:
      - algorithm_images: api/algorithm_images.md
      - algorithm_jobs: api/algorithm_jobs.md
      - algorithms: api/algorithms.md
      - archive_items: api/archive_items.md
      - archives: api/archives.md
      - images: api/images.md
      - interfaces: api/interfaces.md
      - raw_image_upload_sessions: api/raw_image_upload_sessions.md
      - reader_studies:
        - reader_studies: api/reader_studies.md
        - display_sets: api/reader_studies/display_sets.md
        - questions: api/reader_studies/questions.md
        - answers: api/reader_studies/answers.md
        - answers.mine: api/reader_studies/answers_mine.md
      - sessions: api/sessions.md
      - uploads: api/uploads.md
      - workstation_configs: api/workstation_configs.md
    - Models: api/models.md
    - Retries: api/retries.md
repo_url: https://github.com/DIAGNijmegen/rse-gcapi
repo_name: gcapi
edit_uri: docs/


# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      locale: en
      handlers:
        python:
          options:
            show_source: false
            annotations_path: brief
            show_signature_annotations: true
            separate_signature: true
            docstring_section_style: list
            show_bases: false
            extensions:
                - griffe_generics

# Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "¤"


# Theme settings
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    # - toc.follow
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.top
  icon:
    logo: material/connection
    repo: fontawesome/brands/github
  favicon: images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
